version: '2.0'
services:
 mysql:
  image: mariadb 
  volumes:
   - ./db-data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: password
  ports:
   - "3306:3306"
 php:
  build:
   context: .
   dockerfile: Dockerfile-php-fpm
  volumes:
   - ./code:/code
   - ./wordpress:/var/www/html
  links:
   - wordpress
  ports:
   - "9000:9000"
 nginx:
  build: .
  volumes:
   - ./code:/code
   - ./wordpress:/var/www/html
  ports:
   - "80:80"
  links:
   - php
 wordpress:
  image: wordpress:4.7.3
  links:
   - mysql
  volumes:
   - ./wordpress:/var/www/html

  
