version: '2.0'
services:
 mysql:
  image: mariadb 
  volumes:
   - ./db-data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: password
  ports:
   - "3306:3306"
 nginx:
  build: .
  volumes:
   - ./nginx:/etc/nginx/conf.d
   - ./wordpress:/var/www/html
  ports:
   - "80:80"
  links:
   - wordpress
 wordpress:
  image: wordpress:4.7.3-php7.0-fpm
  volumes:
   - ./wordpress:/var/www/html
  links:
   - mysql
  ports:
   - "9000:9000"
  environment:
   - WORDPRESS_DB_NAME=my_database
   - WORDPRESS_TABLE_PREFIX=wp_
   - WORDPRESS_DB_PASSWORD=password

  
